### PR TITLE
Update for Rust

### PR DESCRIPTION
**Pull request by jbgoldman1104**
I've implemented Rust Build Functionality.

### CODE REVIEW

**Comment by KatieHarris2397** [comment]
Hello!  When building Rust code on Windows the artifact name still includes the '\"' such that I get "artifact\".exe" as its name.  If you change line 157 of rust.go from:

extName = strings.Trim(line[7:]+artifactExt, "\"")

to:

extName = strings.ReplaceAll(line[7:]+artifactExt, "\"", "")  

it will correctly remove the '\"'  :)  Also, could you add a note to the user to put the artifact name in the builder.yaml if Builder can't find the artifact created?  Something like "Could not find artifact(s).  Please specify the name(s) in the artifactlist of the builder.yaml" then have it look for that artifact which should be stored in the "BUILDER_ARTIFACT_LIST" env var.  Thanks!

Katie

**Comment by jbgoldman1104** [comment]
Thanks for your advice. I will fix.

**Comment by jbgoldman1104** [comment]
I've fixed issues related to artifact names.

**Comment by KatieHarris2397** [comment]
Hello again 😊! I made a recent update to ensure the `builder` command was working correctly and to update the structure in which directories are created.  Could you replace this code starting at line 38 of rust.go:
`if configPath != "" {
  // ex: C:/Users/Name/Projects/helloworld_19293/workspace/dir
  fullPath = filePath
} else {
  path, _ := os.Getwd()
  //combine local path to newly created tempWorkspace,
  //gets rid of "." in path name
  // ex: C:/Users/Name/Projects + /helloworld_19293/workspace/dir
  fullPath = path + filePath[strings.Index(filePath, ".")+1:]
  os.Setenv("BUILDER_DIR_PATH", path)
}`

with this code:

`if os.Getenv("BUILDER_COMMAND") == "true" {
  fullPath = filePath
} else if configPath != "" {
  // ex: C:/Users/Name/Projects/helloworld_19293/workspace/dir
  fullPath = filePath
} else {
  path, _ := os.Getwd()
  //combine local path to newly created tempWorkspace,
  //gets rid of "." in path name
  // ex: C:/Users/Name/Projects + /helloworld_19293/workspace/dir
  fullPath = path + filePath[strings.Index(filePath, ".")+1:]
  os.Setenv("BUILDER_DIR_PATH", path)
}`

This small addition will allow for the `builder` command to work correctly with my new changes.  Thank you!

Katie

**Comment by jbgoldman1104** [comment]
I have updated as you illustrated.

**Comment by armondhonore** [comment]
@jbgoldman1104 The updates have been test! and Merging in you changes which means we will need to update the Readme to add Rust!!!

**Pull request merged**
